// Photo list. Add images by adding an entry here.
// Fields: file (required), alt (required), title (optional),
// file2x (optional 2x srcset variant), width/height (intrinsic pixel size,
// used for aspect ratio + to prevent layout shift),
// aperture / shutter / iso (optional EXIF — omit any/all if unknown).
const PHOTOS = [
  {
    file: "photos/1.jpg",
    file2x: "photos/1@2x.jpg",
    alt: "A small green seedling sprouting from a weathered piece of driftwood, backlit by sunset trees",
    title: "New Growth",
    width: 1314,
    height: 1600,
    aperture: "f/1.8",
    shutter: "1/2500",
    iso: "100",
  },
  {
    file: "photos/2.jpg",
    file2x: "photos/2@2x.jpg",
    alt: "A gnarled tree root system on a riverbank, with calm water and distant mountains beyond",
    title: "River Bend",
    width: 1600,
    height: 919,
    aperture: "f/8",
    shutter: "1/800",
    iso: "125",
  },
  {
    file: "photos/2-alt.jpg",
    file2x: "photos/2-alt@2x.jpg",
    alt: "A dense winter night sky thick with stars and faint nebulosity",
    title: "Winter Sky",
    width: 1600,
    height: 1067,
    aperture: "f/1.8",
    shutter: "10s",
    iso: "400",
  },
  {
    file: "photos/3.jpg",
    file2x: "photos/3@2x.jpg",
    alt: "A wave breaking over dark rocks, shot low to the water beneath an overhanging ledge",
    title: "Breaking Wave",
    width: 1600,
    height: 1067,
    aperture: "f/4.5",
    shutter: "1/2500",
    iso: "160",
  },
  {
    file: "photos/4.jpg",
    file2x: "photos/4@2x.jpg",
    alt: "An osprey perched on a bare branch against a plain sky, looking off to the side",
    title: "Osprey",
    width: 1600,
    height: 1174,
    aperture: "f/6.3",
    shutter: "1/1000",
    iso: "1600",
  },
  {
    file: "photos/4-alt.jpg",
    file2x: "photos/4-alt@2x.jpg",
    alt: "Long-exposure light trails curving along a dark road at night, stars visible overhead",
    title: "Night Trails",
    width: 1600,
    height: 1109,
    aperture: "f/1.8",
    shutter: "6s",
    iso: "800",
  },
  {
    file: "photos/5.jpg",
    file2x: "photos/5@2x.jpg",
    alt: "Young leaves on a bare branch backlit by a bright, cloudy sky",
    title: "Backlit Leaves",
    width: 1600,
    height: 1229,
    aperture: "f/3.2",
    shutter: "1/3200",
    iso: "100",
  },
  {
    file: "photos/Cruise-11.jpg",
    file2x: "photos/Cruise-11@2x.jpg",
    alt: "A gull walking across white sand with colorful cabanas and palm trees behind it",
    title: "Beach Gull",
    width: 1600,
    height: 1236,
    aperture: "f/5.6",
    shutter: "1/1000",
    iso: "100",
  },
  {
    file: "photos/Cruise-6.jpg",
    file2x: "photos/Cruise-6@2x.jpg",
    alt: "A gull flying low over deep blue ocean water, carrying off a slice of pizza",
    title: "Lunch on the Wing",
    width: 1600,
    height: 1502,
    aperture: "f/5.6",
    shutter: "1/640",
    iso: "100",
  },
  {
    file: "photos/DSC04734.jpg",
    file2x: "photos/DSC04734@2x.jpg",
    alt: "A large white mushroom cap backlit by low morning sun, rising out of green grass",
    title: "Sunrise Mushroom",
    width: 1120,
    height: 1600,
    aperture: "f/14",
    shutter: "1/80",
    iso: "100",
  },
  {
    file: "photos/DSC04739.jpg",
    file2x: "photos/DSC04739@2x.jpg",
    alt: "The same backlit mushroom from a lower angle, with sunlight flaring around its cap",
    title: "Mushroom, Backlit",
    width: 1600,
    height: 1045,
    aperture: "f/14",
    shutter: "1/60",
    iso: "100",
  },
  {
    file: "photos/DSC04807.jpg",
    file2x: "photos/DSC04807@2x.jpg",
    alt: "A duck's head and neck in profile against a blurred green background",
    title: "Duck Portrait",
    width: 1600,
    height: 1285,
    aperture: "f/10",
    shutter: "1/125",
    iso: "200",
  },
  {
    file: "photos/DSC04809.jpg",
    file2x: "photos/DSC04809@2x.jpg",
    alt: "A duck looking directly into the camera, framed by out-of-focus trees",
    title: "Eye Contact",
    width: 1600,
    height: 988,
    aperture: "f/9",
    shutter: "1/640",
    iso: "500",
  },
  {
    file: "photos/DSC04810.jpg",
    file2x: "photos/DSC04810@2x.jpg",
    alt: "A duck swimming with its bill open mid-quack, driftwood in the background",
    title: "Quack",
    width: 1600,
    height: 1091,
    aperture: "f/9",
    shutter: "1/1000",
    iso: "400",
  },
  {
    file: "photos/DSC04824.jpg",
    file2x: "photos/DSC04824@2x.jpg",
    alt: "A small sailboat anchored on a river beneath a large steel truss railroad bridge, framed by leaves",
    title: "Sailboat and Bridge",
    width: 1529,
    height: 1600,
    aperture: "f/5.6",
    shutter: "1/400",
    iso: "100",
  },
  {
    file: "photos/DSC04972.jpg",
    file2x: "photos/DSC04972@2x.jpg",
    alt: "Close-up of barnacles clustered on a rock at low tide, with a rocky shoreline beyond",
    title: "Barnacles",
    width: 1600,
    height: 1067,
    aperture: "f/11",
    shutter: "1/250",
    iso: "125",
  },
  {
    file: "photos/DSC05025.jpg",
    file2x: "photos/DSC05025@2x.jpg",
    alt: "A shallow tide pool threading between dark, weathered rocks",
    title: "Tide Pool",
    width: 1344,
    height: 1600,
    aperture: "f/6.3",
    shutter: "1/800",
    iso: "125",
  },
  {
    file: "photos/DSC05238.jpg",
    file2x: "photos/DSC05238@2x.jpg",
    alt: "A duck balanced on one leg atop a rock, stretching a wing, silhouetted against calm water and hills",
    title: "Balancing Act",
    width: 1198,
    height: 1600,
    aperture: "f/5",
    shutter: "1/2000",
    iso: "200",
  },
  {
    file: "photos/DSC05301.jpg",
    file2x: "photos/DSC05301@2x.jpg",
    alt: "A pale, translucent molted skin caught on a bare twig above rocky ground",
    title: "Molted Skin",
    width: 1600,
    height: 1067,
    aperture: "f/9",
    shutter: "1/2000",
    iso: "500",
  },
  {
    file: "photos/DSC05429.jpg",
    file2x: "photos/DSC05429@2x.jpg",
    alt: "Two Canada geese in tall grass, one with its neck extended and beak open mid-honk",
    title: "Canada Geese",
    width: 1600,
    height: 1067,
    aperture: "f/11",
    shutter: "1/2000",
    iso: "1600",
  },
  {
    file: "photos/DSC05512.jpg",
    file2x: "photos/DSC05512@2x.jpg",
    alt: "A mottled brown duck with a yellow bill resting at the water's edge among rocks",
    title: "At the Water's Edge",
    width: 1600,
    height: 1072,
    aperture: "f/8",
    shutter: "1/1000",
    iso: "500",
  },
  {
    file: "photos/DSC05752.jpg",
    file2x: "photos/DSC05752@2x.jpg",
    alt: "A jet airplane seen from directly below, silhouetted against a cloudy sky",
    title: "Overhead",
    width: 1118,
    height: 1600,
    aperture: "f/11",
    shutter: "1/2000",
    iso: "160",
  },
  {
    file: "photos/DSC05851.jpg",
    file2x: "photos/DSC05851@2x.jpg",
    alt: "A Delta jet's wings and engines seen from below against a clear blue sky",
    title: "Delta",
    width: 1600,
    height: 1189,
    aperture: "f/10",
    shutter: "1/2000",
    iso: "800",
  },
  {
    file: "photos/DSC05995.jpg",
    file2x: "photos/DSC05995@2x.jpg",
    alt: "Small flower buds on a stem, lit against a near-black background",
    title: "Buds",
    width: 1245,
    height: 1600,
    aperture: "f/1.8",
    shutter: "1/40",
    iso: "200",
  },
  {
    file: "photos/DSC06051.jpg",
    file2x: "photos/DSC06051@2x.jpg",
    alt: "A starry night sky over a backyard pergola, with a house glowing warmly below",
    title: "Stars Over the Backyard",
    width: 1600,
    height: 1055,
    aperture: "f/1.8",
    shutter: "10s",
    iso: "250",
  },
  {
    file: "photos/DSC06052.jpg",
    file2x: "photos/DSC06052@2x.jpg",
    alt: "A dense field of stars with a faint band of the Milky Way",
    title: "Deep Sky",
    width: 1600,
    height: 1067,
    aperture: "f/1.8",
    shutter: "10s",
    iso: "640",
  },
  {
    file: "photos/DSC06058.jpg",
    file2x: "photos/DSC06058@2x.jpg",
    alt: "A starry sky with the silhouette of a pine tree at the left edge",
    title: "Pine and Stars",
    width: 1600,
    height: 1067,
    aperture: "f/1.8",
    shutter: "8s",
    iso: "800",
  },
  {
    file: "photos/DSC06060.jpg",
    file2x: "photos/DSC06060@2x.jpg",
    alt: "A starry sky over a dark treeline silhouette",
    title: "Treeline",
    width: 1600,
    height: 1067,
    aperture: "f/1.8",
    shutter: "8s",
    iso: "800",
  },
  {
    file: "photos/DSC06061.jpg",
    file2x: "photos/DSC06061@2x.jpg",
    alt: "A starry sky framed by trees on either side, with a faint meteor streak",
    title: "Meteor",
    width: 1600,
    height: 968,
    aperture: "f/1.8",
    shutter: "8s",
    iso: "800",
  },
  {
    file: "photos/DSC06067.jpg",
    file2x: "photos/DSC06067@2x.jpg",
    alt: "A wide, minimal starfield with two faint meteor streaks",
    title: "Falling Stars",
    width: 1600,
    height: 1067,
    aperture: "f/1.8",
    shutter: "10s",
    iso: "100",
  },
];
